name: Unit-Testing

on:
  # set triggers here, like on push or on release
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.20.x

      - name: Install dependencies
        run: yarn install

      - name: Testing
        run: yarn test
