name: Unit-Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.0
        with:
          version: 6.23.x

      - name: Install dependencies
        run: pnpm i

      - name: Testing
        run: pnpm test:coverage
        env:
          CI: true
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
